"""Consolidated re-exports for large service/client imports used by the app.
This module mirrors the long import lists previously embedded in `cosi_app.py`.
Keep this file lightweight: no side-effects, only imports and re-exports.
"""
from app.server import (
    # Gmail MCP
    send_email,
    # search_emails,  # Removed - now using MongoDB
    search_sent_emails,
    draft_email,
    list_email_drafts,
    get_email_draft,
    # query_emails,  # Removed - now using MongoDB
    download_attachments,
    list_available_labels,
    # mark_message_read,  # Merged into update_email
    # add_label_to_message,  # Merged into update_email
    # remove_label_from_message,  # Merged into update_email
    # get_emails,  # Removed - now using MongoDB
    # star_email,  # Merged into update_email
    # unstar_email,  # Merged into update_email
    # delete_email,  # Merged into update_email
    update_email,  # NEW: Unified email update function
    create_gmail_label,
    delete_gmail_label,
    # get_unread_emails,  # New function for unread emails from API
    # get_unread_emails_db,
    # get_starred_emails,
    # get_emails_from,
    # get_emails_to,
    # search_emails_by_date_tool,
    # Calendar MCP
    # get_calendar_service,
    create_event,
    delete_event,
    get_event,
    search_events,
    delete_events_by_filter,
    update_calendar_event,
    # Slack MCP
    send_slack_messages,
    slack_list_channels,
    get_channels,
    get_channel_messages,
    # get_channel_info,
    list_users,
    get_channel_members,
    get_user_info,
    create_channel,
    archive_channel,
    invite_user_to_channel,
    kick_user_from_channel,
    pin_message,
    unpin_message,
    # react_to_message,
    get_dm_messages,
    send_dm,
    # open_dm_with_user,
    # upload_file,
    slack_reply_message as reply_message,
    # Google Documents MCP
    # get_user_documents,
    # get_document_content,  # Replaced with mongo_get_docs from MongoDB
    create_document,
    update_document_text,
    update_document_image,
    add_document_comment,
    update_document_table,
    get_document_table_content,
    delete_document,
    share_document,
    search_in_document,
    # search_docs,
    doc_history,
    generate_doc_from_link,
    search_docs_by_date_tool,
    list_docs_tool,
    # Google Sheets MCP
    list_sheets,
    create_sheet,
    read_sheet_data,
    # write_sheet_data,
    # append_sheet_data,
    clear_sheet_range,
    add_new_tab,
    delete_sheet_tab,
    share_sheet,
    search_sheets,
    sheet_history,
    add_sheet_comment,
    list_sheet_info,
    update_sheet_data,
    sheet_chart_metadata,
    sheet_create_chart,
    sheet_update_chart,
    sheet_create_pivot_table,
    # Google Slides MCP
    list_slides,
    create_slide_deck,
    share_slide_deck,
    extract_text_from_slides,
    get_slide_content,
    get_specific_slide,
    replace_text_in_slides,
    add_text_box_to_slide,
    add_slide_to_presentation,
    format_text_in_slides,
    search_slides,
    # slide_history,
    # add_table_to_slide,
    # update_table_cell,
    # populate_table,
    # add_table_rows,
    # add_table_columns,
    # delete_table_rows,
    # delete_table_columns,
    # insert_row_above,
    # insert_row_below,
    # insert_column_left,
    # insert_column_right,
    # # New powerful tools from gSlides_ai
    # list_slide_elements,
    # list_tables,
    # get_table_info,
    # read_table_data,
    # replace_table_text,
    # search_presentation,
    # get_element_text,
    # delete_element,
    # delete_slide,
    # insert_text,
    # insert_image,
    # list_slides_info,
    # add_rows_and_populate,
    # append_table_row,
    # add_columns_and_populate,
    # append_table_column,
    # Gamma Presentation
    create_gamma_presentation,
    # list_gamma_themes,
    # Notion MCP
    list_databases,
    list_pages,
    create_page,
    create_database,
    create_parent_page,
    find_or_create_database,
    list_parent_pages,
    search_notion,
    append_block,
    update_block,
    delete_block,
    get_page_content,
    get_notion_comment,
    notion_add_comment,
    update_page_title,
    update_page_properties,
    delete_page,
    add_todo,
    query_database,
    get_documents,
    get_database_schema,
    # get_tasks_detailed,
    # create_task,
    # find_tasks_tracker_db,
    # Trello Task Manager MCP
    task_list_boards,
    task_list_members,
    task_list_lists,
    task_list_cards,
    task_create,
    task_update,
    task_move,
    task_delete,
    task_search,
    task_get,
    task_comment_add,
    task_comment_list,
    task_comment_update,
    task_comment_delete,
    task_members_add,
    task_member_remove,
    task_label_add,
    task_label_remove,
    task_list_board_labels,
    task_board_label_create,
    task_board_label_update,
    task_checklist_create,
    task_checklists,
    task_checkitem_add,
    task_checkitem_update,
    task_checkitem_delete,
    task_attachment_add_url,
    task_set_custom_field,
    task_list_create,
    task_find_board,
    task_find_list,
)

# Import error handling utilities
from utils.error_handler import (
    wrap_tool_execution,
    handle_api_error,
    log_error_to_terminal,
    get_user_friendly_error_message,
    tool_status_error_message,
)

# Import MongoDB functions directly
from clients.mongo_email_client import mongo_query_emails, mongo_get_emails
from clients.mongo_docs_client import (
    mongo_search_docs,
    mongo_query_docs,
    mongo_get_docs,
    search_docs_by_date,
    list_docs,
)
from clients.mongo_calendar_client import (
    mongo_search_events,
    mongo_query_events,
    mongo_get_events,
)
from services.transcript_mcp import get_meeting_transcript
# from clients.mongo_context_client import (
#     get_email_context,
#     get_calendar_context,
#     get_docs_context,
#     get_slides_context,
#     get_notion_context,
#     get_trello_context,
#     get_slack_context,
# )
from clients.mongo_briefing_client import (
    get_latest_briefing,
    get_all_latest_briefings,
    # Legacy functions for backward compatibility
    # get_latest_gmail_briefing,
    # get_latest_calendar_briefing,
)
from clients.qdrant_vector_client import vector_context_search
from clients.db_method import get_distinct_gmail_senders, user_info
from clients.mongo_personalization_client import get_user_personality, get_user_profile_collection
from clients.mongo_history_client import save_chat_history
from services.openai_web_search import web_search as openai_web_search


# Build a tools registry that maps tool names to callables (lambdas) using
# the functions imported above. This keeps the large mapping centralized.
tools = {
    "send_email": lambda **kwargs: send_email(**kwargs),
    "search_emails": lambda **kwargs: mongo_query_emails(**kwargs),
    "search_sent_emails": lambda **kwargs: search_sent_emails(**kwargs),
    "draft_email": lambda **kwargs: draft_email(**kwargs),
    "list_email_drafts": lambda **kwargs: list_email_drafts(**kwargs),
    "get_email_draft": lambda **kwargs: get_email_draft(**kwargs),
    "list_available_labels": lambda **kwargs: list_available_labels(**kwargs),
    "get_emails": lambda **kwargs: mongo_get_emails(**kwargs),
    "get_latest_briefing": lambda **kwargs: get_latest_briefing(**kwargs),
    "vector_context_search": lambda **kwargs: vector_context_search(**kwargs),
    "download_attachments": lambda **kwargs: download_attachments(**kwargs),
    "update_email": lambda **kwargs: update_email(**kwargs),
    "create_gmail_label": lambda **kwargs: create_gmail_label(**kwargs),
    "create_event": lambda **kwargs: create_event(**kwargs),
    "get_event": lambda **kwargs: get_event(**kwargs),
    "update_event": lambda **kwargs: update_calendar_event(**kwargs),
    "search_calendar_events": lambda **kwargs: mongo_search_events(**kwargs),
    "query_events": lambda **kwargs: mongo_query_events(**kwargs),
    "get_events": lambda **kwargs: mongo_get_events(**kwargs),
    "get_meeting_transcript": lambda **kwargs: get_meeting_transcript(**kwargs),
    # "get_calendar_context": lambda **kwargs: get_calendar_context(**kwargs),
    "delete_events": lambda **kwargs: delete_events_by_filter(**kwargs),
    "get_channels": lambda **kwargs: get_channels(**kwargs),
    "send_slack_messages": lambda **kwargs: send_slack_messages(**kwargs),
    "get_channel_messages": lambda **kwargs: get_channel_messages(
        kwargs.get("channel"), kwargs.get("limit", 100), kwargs.get("token", "token"), kwargs.get("order", "desc")
    ),
    "list_users": lambda **kwargs: list_users(**kwargs),
    "get_channel_members": lambda **kwargs: get_channel_members(**kwargs),
    "get_user_info": lambda **kwargs: get_user_info(**kwargs),
    "create_channel": lambda **kwargs: create_channel(**kwargs),
    "invite_user_to_channel": lambda **kwargs: invite_user_to_channel(**kwargs),
    "pin_message": lambda **kwargs: pin_message(**kwargs),
    "get_dm_messages": lambda **kwargs: get_dm_messages(**kwargs),
    "send_dm": lambda **kwargs: send_dm(**kwargs),
    "reply_message": lambda **kwargs: reply_message(**kwargs),
    # "get_slack_context": lambda **kwargs: get_slack_context(**kwargs),
    "get_document_content": lambda **kwargs: mongo_get_docs(**kwargs),
    "create_document": lambda **kwargs: create_document(**kwargs),
    "update_document_text": lambda **kwargs: update_document_text(**kwargs),
    "update_document_image": lambda **kwargs: update_document_image(**kwargs),
    "add_document_comment": lambda **kwargs: add_document_comment(**kwargs),
    "update_document_table": lambda **kwargs: update_document_table(**kwargs),
    "get_document_table_content": lambda **kwargs: get_document_table_content(**kwargs),
    "delete_document": lambda **kwargs: delete_document(**kwargs),
    "share_document": lambda **kwargs: share_document(**kwargs),
    "search_in_document": lambda **kwargs: search_in_document(**kwargs),
    "query_docs": lambda **kwargs: mongo_query_docs(**kwargs),
    # "get_docs_context": lambda **kwargs: get_docs_context(**kwargs),
    "doc_history": lambda **kwargs: doc_history(**kwargs),
    "generate_doc_from_link": lambda **kwargs: generate_doc_from_link(**kwargs),
    "search_docs_by_date": lambda **kwargs: search_docs_by_date_tool(**kwargs),
    "list_docs": lambda **kwargs: list_docs_tool(**kwargs),
    "list_sheets": lambda **kwargs: list_sheets(**kwargs),
    "create_sheet": lambda **kwargs: create_sheet(**kwargs),
    "read_sheet_data": lambda **kwargs: read_sheet_data(**kwargs),
    "clear_sheet_range": lambda **kwargs: clear_sheet_range(**kwargs),
    "add_new_tab": lambda **kwargs: add_new_tab(**kwargs),
    "delete_sheet_tab": lambda **kwargs: delete_sheet_tab(**kwargs),
    "share_sheet": lambda **kwargs: share_sheet(**kwargs),
    "search_sheets": lambda **kwargs: search_sheets(**kwargs),
    "sheet_history": lambda **kwargs: sheet_history(**kwargs),
    "add_sheet_comment": lambda **kwargs: add_sheet_comment(**kwargs),
    "list_sheet_info": lambda **kwargs: list_sheet_info(**kwargs),
    "update_sheet_data": lambda **kwargs: update_sheet_data(**kwargs),
    "sheet_chart_metadata": lambda **kwargs: sheet_chart_metadata(**kwargs),
    "sheet_create_chart": lambda **kwargs: sheet_create_chart(**kwargs),
    "sheet_update_chart": lambda **kwargs: sheet_update_chart(**kwargs),
    "sheet_create_pivot_table": lambda **kwargs: sheet_create_pivot_table(**kwargs),
    "list_slides": lambda **kwargs: list_slides(**kwargs),
    "share_slide_deck": lambda **kwargs: share_slide_deck(**kwargs),
    "extract_text_from_slides": lambda **kwargs: extract_text_from_slides(**kwargs),
    "get_slide_content": lambda **kwargs: get_slide_content(**kwargs),
    "get_specific_slide": lambda **kwargs: get_specific_slide(**kwargs),
    "replace_text_in_slides": lambda **kwargs: replace_text_in_slides(**kwargs),
    "add_text_box_to_slide": lambda **kwargs: add_text_box_to_slide(**kwargs),
    "add_slide_to_presentation": lambda **kwargs: add_slide_to_presentation(**kwargs),
    "format_text_in_slides": lambda **kwargs: format_text_in_slides(**kwargs),
    "search_slides": lambda **kwargs: search_slides(**kwargs),
    "web_search": lambda **kwargs: openai_web_search(**kwargs),
    # "get_slides_context": lambda **kwargs: get_slides_context(**kwargs),
    "create_gamma_presentation": lambda **kwargs: create_gamma_presentation(**kwargs),
    # "list_gamma_themes": lambda **kwargs: list_gamma_themes(**kwargs),
    "list_databases": lambda **kwargs: list_databases(**kwargs),
    "get_notion_documents": lambda **kwargs: get_documents(**kwargs),
    "list_pages": lambda **kwargs: list_pages(**kwargs),
    "create_page": lambda **kwargs: create_page(**kwargs),
    "create_database": lambda **kwargs: create_database(**kwargs),
    "create_parent_page": lambda **kwargs: create_parent_page(**kwargs),
    "find_or_create_database": lambda **kwargs: find_or_create_database(**kwargs),
    "list_parent_pages": lambda **kwargs: list_parent_pages(**kwargs),
    "search_notion": lambda **kwargs: search_notion(**kwargs),
    "append_block": lambda **kwargs: append_block(**kwargs),
    "update_block": lambda **kwargs: update_block(**kwargs),
    "delete_block": lambda **kwargs: delete_block(**kwargs),
    "get_page_content": lambda **kwargs: get_page_content(**kwargs),
    "get_notion_comment": lambda **kwargs: get_notion_comment(**kwargs),
    "notion_add_comment": lambda **kwargs: notion_add_comment(**kwargs),
    "update_page_title": lambda **kwargs: update_page_title(**kwargs),
    "update_page_properties": lambda **kwargs: update_page_properties(**kwargs),
    "delete_page": lambda **kwargs: delete_page(**kwargs),
    "add_todo": lambda **kwargs: add_todo(**kwargs),
    "query_database": lambda **kwargs: query_database(**kwargs),
    "get_database_schema": lambda **kwargs: get_database_schema(**kwargs),
    "list_task_boards": lambda **kwargs: task_list_boards(**kwargs),
    "find_task_board": lambda **kwargs: task_find_board(**kwargs),
    "list_task_members": lambda **kwargs: task_list_members(**kwargs),
    "list_task_lists": lambda **kwargs: task_list_lists(**kwargs),
    "list_task_cards": lambda **kwargs: task_list_cards(**kwargs),
    "create_task": lambda **kwargs: task_create(**kwargs),
    "update_task": lambda **kwargs: task_update(**kwargs),
    "move_task": lambda **kwargs: task_move(**kwargs),
    "delete_task": lambda **kwargs: task_delete(**kwargs),
    "search_tasks": lambda **kwargs: task_search(**kwargs),
    "get_task": lambda **kwargs: task_get(**kwargs),
    "add_task_comment": lambda **kwargs: task_comment_add(**kwargs),
    "task_comment_list": lambda **kwargs: task_comment_list(**kwargs),
    "update_task_comment": lambda **kwargs: task_comment_update(**kwargs),
    "delete_task_comment": lambda **kwargs: task_comment_delete(**kwargs),
    "add_task_members": lambda **kwargs: task_members_add(**kwargs),
    "remove_task_member": lambda **kwargs: task_member_remove(**kwargs),
    "add_task_label": lambda **kwargs: task_label_add(**kwargs),
    "remove_task_label": lambda **kwargs: task_label_remove(**kwargs),
    "list_task_board_labels": lambda **kwargs: task_list_board_labels(**kwargs),
    "create_board_label": lambda **kwargs: task_board_label_create(**kwargs),
    "update_board_label": lambda **kwargs: task_board_label_update(**kwargs),
    "create_task_checklist": lambda **kwargs: task_checklist_create(**kwargs),
    "list_task_checklists": lambda **kwargs: task_checklists(**kwargs),
    "add_task_checkitem": lambda **kwargs: task_checkitem_add(**kwargs),
    "update_task_checkitem": lambda **kwargs: task_checkitem_update(**kwargs),
    "delete_task_checkitem": lambda **kwargs: task_checkitem_delete(**kwargs),
    "add_task_attachment_url": lambda **kwargs: task_attachment_add_url(**kwargs),
    "set_task_custom_field": lambda **kwargs: task_set_custom_field(**kwargs),
    "create_task_list": lambda **kwargs: task_list_create(**kwargs),
    "find_task_list": lambda **kwargs: task_find_list(**kwargs),
    # "get_trello_context": lambda **kwargs: get_trello_context(**kwargs),
}
